spring:
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: localhost:9092
    security-protocol:
    consumer:
      group-id: my-owl-group-id
      enable-auto-commit: false
      auto-commit-interval: 1000
      auto-offset-reset: earliest
    template:
      default-topic: toRing #inventory
    sasl:
      mechanism:
      jaas-config:
    ssl:
      trust-store-location:
      trust-store-password:
    properties:
      schema-registry-url: http://localhost:8081
      basic-auth-credentials-source:
      schema-registry-basic-auth-user-info: