spring:
  kafka:
    bootstrap-servers: localhost:9092
    security-protocol:
    template:
      default-topic: inventory
    sasl:
      mechanism:
      jaas-config:
    ssl:
      trust-store-location:
      trust-store-password:
    properties:
      schema-registry-url: http://localhost:8081
      basic-auth-credentials-source:
      schema-registry-basic-auth-user-info: