spring:
  kafka:
    bootstrap-servers: {TO COMPLETE}
    security-protocol: {TO COMPLETE}
    template:
      default-topic: inventory
    sasl:
      mechanism: {TO COMPLETE}
      jaas-config: {TO COMPLETE}
    ssl:
      trust-store-location: {TO COMPLETE}
      trust-store-password: {TO COMPLETE}
    properties:
      schema-registry-url: {TO COMPLETE}
      basic-auth-credentials-source: {TO COMPLETE}
      schema-registry-basic-auth-user-info: {TO COMPLETE}