spring:
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: localhost:9092
    security-protocol:
    application-id: my-kstream-id
    input-topic-name: inventory
    output-topic-name: toRing
    sasl:
      mechanism:
      jaas-config:
      ssl:
        trust-store-location:
        trust-store-password:
    properties:
      schema-registry-url: http://localhost:8081
      basic-auth-credentials-source:
      schema-registry-basic-auth-user-info: